# Generated by Django 2.1.5 on 2022-08-14 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrp', '0002_auto_20220814_0934'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('requestUser', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rrp.Users')),
            ],
        ),
    ]
