# Generated by Django 2.1.5 on 2022-08-16 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrp', '0004_auto_20220814_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('assetName', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('assetType', models.CharField(max_length=30, null=True)),
                ('dataLevel', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ransomware',
            fields=[
                ('ransomwareName', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('ransomwareType', models.CharField(max_length=30, null=True)),
                ('description', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
