# Generated by Django 2.1.5 on 2022-08-16 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rrp', '0005_asset_ransomware'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='assetType',
            new_name='assetName',
        ),
    ]
