# Generated by Django 2.1.5 on 2022-08-16 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrp', '0007_event_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskLevelAssessment',
            fields=[
                ('dataLevel', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('ransomwareType', models.CharField(max_length=30, null=True)),
                ('riskLevel', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
