# Generated by Django 2.1.5 on 2022-08-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrp', '0008_risklevelassessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='risklevelassessment',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='risklevelassessment',
            name='dataLevel',
            field=models.CharField(max_length=30),
        ),
    ]
