# Generated by Django 2.1.5 on 2022-08-17 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrp', '0009_auto_20220817_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='assetName',
        ),
        migrations.AddField(
            model_name='event',
            name='ransomware',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rrp.Ransomware'),
        ),
        migrations.AddField(
            model_name='event',
            name='userAsset',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rrp.Asset'),
        ),
    ]
