# Generated by Django 2.1.5 on 2022-08-19 15:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rrp', '0010_auto_20220817_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Handler',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.RemoveField(
            model_name='event',
            name='reporters',
        ),
        migrations.AddField(
            model_name='event',
            name='reporters',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
