# Generated by Django 2.1.5 on 2022-08-20 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrp', '0013_auto_20220819_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='cirt',
            field=models.BooleanField(default=False),
        ),
    ]
