# Generated by Django 2.1.5 on 2022-08-20 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrp', '0014_users_cirt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30, null=True)),
                ('info', models.TextField(max_length=1000, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='records',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='recoveryInfo',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
