# Generated by Django 2.1.5 on 2022-08-20 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrp', '0015_auto_20220820_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('eventId', models.IntegerField(null=True)),
                ('picURL', models.ImageField(blank=True, upload_to='evidence_images')),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='evidence',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='rrp.Evidence'),
        ),
    ]
