# Generated by Django 2.1.5 on 2022-08-21 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrp', '0016_auto_20220820_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='evidence',
        ),
        migrations.AddField(
            model_name='event',
            name='evidence',
            field=models.ManyToManyField(blank=True, default=None, to='rrp.Evidence'),
        ),
    ]
