# Generated by Django 2.1.5 on 2022-08-21 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrp', '0017_auto_20220821_0131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='evidence',
        ),
        migrations.AlterField(
            model_name='evidence',
            name='eventId',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='rrp.Event'),
        ),
    ]
